---
deployment:
    tasks:
        - export DEPLOYPATH=/home/jaehivaf/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp gallery.html $DEPLOYPATH
        - /bin/cp about.html $DEPLOYPATH
        - /bin/cp contact.html $DEPLOYPATH
        - /bin/cp ./js/darkModeToggle.js $DEPLOYPATH/js
        - /bin/cp -r ./assets/imgs/boston/. $DEPLOYPATH/assets/imgs/boston
        - /bin/cp -r ./assets/imgs/headshots/. $DEPLOYPATH/assets/imgs/headshots
        - /bin/cp -r ./assets/imgs/london/. $DEPLOYPATH/assets/imgs/london
        - /bin/cp -r ./assets/imgs/newyork/. $DEPLOYPATH/assets/imgs/newyork
