---
deployment:
    tasks:
        - export DEPLOYPATH=/home/jaehivaf/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp gallery.html $DEPLOYPATH
        - /bin/cp about.html $DEPLOYPATH
        - /bin/cp contact.html $DEPLOYPATH
        - /bin/cp ./js/darkModeToggle.js $DEPLOYPATH/js
